# Generated by Django 5.1.1 on 2024-09-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
